#ifndef PI
#define PI 3.14159265359
#endif

#ifndef EPSILON
#define EPSILON 0.0001
#endif

#ifndef ROTATION_FACTOR
#define ROTATION_FACTOR 360.0
#endif

#ifndef X_VIEW_CLAMP
#define X_VIEW_CLAMP 1130.0
#endif

#ifndef Y_VIEW_CLAMP
#define Y_VIEW_CLAMP 960.0
#endif

#ifndef HIGHLIGHT_OUTLINE_COLOR
#define HIGHLIGHT_OUTLINE_COLOR 0xFFFFFF
#endif

#ifndef DEFAULT_OUTLINE_COLOR
#define DEFAULT_OUTLINE_COLOR 0xA0A0A0
#endif

#define BLOCK_FACE_TOP 0
#define BLOCK_FACE_BOTTOM 1
#define BLOCK_FACE_FRONT 2
#define BLOCK_FACE_BACK 3
#define BLOCK_FACE_RIGHT 4
#define BLOCK_FACE_LEFT 5
#define BLOCK_FACE_NONE -1
